apiVersion: v1
kind: Namespace
metadata:
  name: dev
  labels:
    name: dev

---

apiVersion: v1
kind: Namespace
metadata:
  name: prod
  labels:
    name: prod

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dev
  namespace: dev
  labels:
    app: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      annotations:
        change-cause: "Change to port 100"
      labels:
        app: front
    spec:
      containers:
      - name: nginx
        image: nginx:alpine

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-prod
  namespace: prod
  labels:
    app: back
spec:
  replicas: 2
  selector:
    matchLabels:
      app: back
  template:
    metadata:
      annotations:
        change-cause: "Change to port 100"
      labels:
        app: back
    spec:
      containers:
      - name: nginx
        image: nginx:alpine